"""
Current business schema baseline.
Revision ID: 0001_uuid_baseline
Revises:
- 乐观锁 ``version`` 列直接写进 ``content_items`` / ``boards`` / ``articles``
  的 create_table，无需事后 ``add_column``；
- ``upload_sessions`` 表（预签名直传元数据落 DB）作为普通建表；
- ``points_ledger`` 直接建成能承载 continuous aggregate 的形态：复合主键
  ``(created_at, id)`` + 含分区列的幂等唯一约束（约束名 ``uq_points_ledger_ref`` 不变，
  ``pg_upsert`` 按名解析 arbiter），hypertable 装配并入下方 ``TIMESCALE_DDL``。
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001_uuid_baseline'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

UUID7_FUNCTION_SQL = """
CREATE OR REPLACE FUNCTION public.uuid_generate_v7() RETURNS uuid AS $$
DECLARE
  us bigint;
  b  bytea;
BEGIN
  us := (extract(epoch FROM clock_timestamp()) * 1000000)::bigint;
  b  := uuid_send(gen_random_uuid());
  b  := overlay(b PLACING substring(int8send(us >> 12) FROM 3) FROM 1 FOR 6);
  b  := set_byte(b, 6, (112 + ((us >> 8) & 15))::int);
  b  := set_byte(b, 7, (us & 255)::int);
  b  := set_byte(b, 8, (get_byte(b, 8) & 63) + 128);
  RETURN encode(b, 'hex')::uuid;
END;
$$ LANGUAGE plpgsql VOLATILE;
"""

TIMESCALE_DDL = """
DO $$
BEGIN
  BEGIN
    CREATE EXTENSION IF NOT EXISTS timescaledb;
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'timescaledb 不可用，outbox/points_ledger 保持普通表：%', SQLERRM;
  END;

  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'timescaledb') THEN
    -- 整段装配再包一层 EXCEPTION：扩展在、但装配本身失败（版本差异导致函数签名不符、
    -- 托管实例权限不足、表无法转换）时只告警，不中断整条基线迁移。内层 savepoint 回滚后
    -- 各表保持普通表可用，与上面「失败仅告警不中断」的约定一致。
    BEGIN
      PERFORM create_hypertable('outbox_events', 'created_at',
          chunk_time_interval => INTERVAL '7 days',
          if_not_exists => TRUE, migrate_data => TRUE);
      PERFORM create_hypertable('outbox_archived', 'created_at',
          chunk_time_interval => INTERVAL '7 days',
          if_not_exists => TRUE, migrate_data => TRUE);
      PERFORM create_hypertable('points_ledger', 'created_at',
          chunk_time_interval => INTERVAL '7 days',
          if_not_exists => TRUE, migrate_data => TRUE);
      ALTER TABLE outbox_archived SET (
          timescaledb.compress,
          timescaledb.compress_segmentby = 'routing_key',
          timescaledb.compress_orderby = 'created_at DESC');
      PERFORM add_compression_policy('outbox_archived', INTERVAL '7 days',
          if_not_exists => TRUE);
    EXCEPTION WHEN OTHERS THEN
      RAISE WARNING 'timescaledb 装配失败，outbox/points_ledger 保持普通表：%', SQLERRM;
    END;
  END IF;
END $$;
"""


def upgrade() -> None:
    """Upgrade schema."""
    # 建表前置共享对象一：pg_trgm 扩展——content_items 的 trgm GIN 索引 opclass
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm SCHEMA public")
    # 建表前置共享对象二：uuid7 生成函数（所有 UUID 主键列的 server_default 目标）
    op.execute(UUID7_FUNCTION_SQL)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('key', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=80), nullable=False),
    sa.Column('name_key', sa.String(length=120), nullable=False),
    sa.Column('desc_key', sa.String(length=160), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('article_categories',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('blog_repo_quarantine',
    sa.Column('repo_name', sa.String(length=120), nullable=False),
    sa.Column('src_dir', sa.String(length=500), nullable=False),
    sa.Column('quarantined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_name', name='uq_blog_repo_quarantine_repo_name')
    )
    op.create_table('blog_series',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('repo_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_name')
    )
    op.create_table('board_applications',
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('boards',
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('require_certified', sa.Boolean(), nullable=False),
    sa.Column('daily_post_limit', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_boards_parent_id'), 'boards', ['parent_id'], unique=False)
    op.create_table('column_applications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dlq_messages',
    sa.Column('routing_key', sa.String(length=255), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exchange', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requeued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_message_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dlq_messages_routing_key'), 'dlq_messages', ['routing_key'], unique=False)
    op.create_index(op.f('ix_dlq_messages_status'), 'dlq_messages', ['status'], unique=False)
    op.create_index('uq_dlq_source_message_id', 'dlq_messages', ['source_message_id'], unique=True)
    op.create_table('event_failures',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('routing_key', sa.String(length=64), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('folded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('replayed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_failures_event_id'), 'event_failures', ['event_id'], unique=False)
    op.create_table('event_processed',
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'event_id')
    )
    op.create_table('exams',
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pass_score', sa.Integer(), nullable=False),
    sa.Column('time_limit_min', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('unlock_level', sa.String(length=10), nullable=True),
    sa.Column('unlock_role', sa.String(length=20), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_items',
    sa.Column('key', sa.String(length=10), nullable=False),
    sa.Column('name_key', sa.String(length=120), nullable=False),
    sa.Column('desc_key', sa.String(length=200), nullable=False),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('is_virtual', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('feed_fanout_state',
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('last_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('source')
    )
    op.create_table('feed_items',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('board_id', sa.Uuid(), nullable=True),
    sa.Column('sort_score', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_preview', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', 'source_id', name='uq_feed_item')
    )
    op.create_index('ix_feed_items_source', 'feed_items', ['source_id', 'item_type'], unique=False)
    op.create_index('ix_feed_items_user_cursor', 'feed_items', ['user_id', 'created_at', 'source_id'], unique=False)
    op.create_table('library_files',
    sa.Column('uploader_id', sa.Uuid(), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('sha3_hash', sa.String(length=64), nullable=True),
    sa.Column('document_code', sa.String(length=40), nullable=True),
    sa.Column('classification', sa.String(length=20), server_default='public', nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('root_file_id', sa.Uuid(), nullable=True),
    sa.Column('extracted_text', sa.Text(), server_default='', nullable=False),
    sa.Column('archive_state', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('backed_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ref_count', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['root_file_id'], ['library_files.id'], name='fk_library_files_root'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name'),
    sa.UniqueConstraint('document_code', 'version', name='uq_library_document_version')
    )
    op.create_index('ix_library_files_sha3_hash', 'library_files', ['sha3_hash'])
    op.create_index('ix_library_files_project', 'library_files', ['project_id'])
    op.create_index('ix_library_files_root_version', 'library_files', ['root_file_id', 'version'])
    op.create_index('ix_library_files_name_trgm', 'library_files', ['original_name'], unique=False, postgresql_using='gin', postgresql_ops={'original_name': 'public.gin_trgm_ops'})
    op.create_index('ix_library_files_text_trgm', 'library_files', ['extracted_text'], unique=False, postgresql_using='gin', postgresql_ops={'extracted_text': 'public.gin_trgm_ops'})
    op.create_table('moderation_rules',
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'type')
    )
    op.create_table('notification_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'token', name='uq_notification_token')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_aggregate', 'notifications', ['user_id', 'type', 'actor_id', 'target_id', 'read_at'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id', 'id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('outbox_event_keys',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('outbox_archived',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('routing_key', sa.String(length=64), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    # 复合主键含分区列 created_at：本表是 hypertable（见 TIMESCALE_DDL 与 app/db/outbox_archive.py）
    sa.PrimaryKeyConstraint('created_at', 'id')
    )
    op.create_index(op.f('ix_outbox_archived_event_id'), 'outbox_archived', ['event_id'], unique=False)
    op.create_index('ix_outbox_archived_published_at', 'outbox_archived', ['published_at'], unique=False)
    op.create_table('outbox_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('routing_key', sa.String(length=64), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('created_at', 'id'),
    sa.UniqueConstraint('event_id', 'created_at')
    )
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_index('ix_outbox_scan', 'outbox_events', ['status', 'next_retry_at'], unique=False)
    op.create_table('points_ledger',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('ref_type', sa.String(length=50), nullable=False),
    sa.Column('ref_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('created_at', 'id'),
    sa.UniqueConstraint('user_id', 'ref_type', 'ref_id', 'created_at', name='uq_points_ledger_ref')
    )
    op.create_index('ix_ledger_created_delta', 'points_ledger', ['created_at', 'delta'], unique=False)
    op.create_table('project_applications',
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('member_claims', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_project_applications_pending', 'project_applications', ['applicant_id', 'title'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    op.create_table('projects',
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('is_incubated', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('is_recruiting', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('team_intro', sa.Text(), nullable=True),
    sa.Column('recruiting_roles', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('reports', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key('fk_library_files_project', 'library_files', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_table('qa_answers',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    # qa_answers ↔ qa_questions 互为外键（循环依赖），建表期无法互相引用：
    # 此 FK 延后到 qa_questions 建出后补加（见下方 create_foreign_key）
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qa_answer_question', 'qa_answers', ['question_id'], unique=False)
    op.create_index('ix_qa_answer_question_accepted', 'qa_answers', ['question_id', 'is_accepted'], unique=False)
    op.create_table('qa_questions',
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('situation', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('bounty_people', sa.Integer(), nullable=False),
    sa.Column('bounty_per_person', sa.Integer(), nullable=False),
    sa.Column('bounty_total', sa.Integer(), nullable=False),
    sa.Column('bounty_distributed', sa.Integer(), nullable=False),
    sa.Column('bounty_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('urgent', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('accepted_answer_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_answer_id'], ['qa_answers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qa_question_category_id', 'qa_questions', ['category', 'id'], unique=False)
    op.create_index('ix_qa_question_status_id', 'qa_questions', ['status', 'id'], unique=False)
    op.create_index('ix_qa_questions_due', 'qa_questions', ['status', 'bounty_expires_at'])
    op.create_index('ix_qa_questions_bounty_sort', 'qa_questions', ['category', 'bounty_total', 'id'])
    # 补上 qa_answers → qa_questions 的循环外键
    op.create_foreign_key(
        'fk_qa_answers_question_id', 'qa_answers', 'qa_questions', ['question_id'], ['id']
    )
    op.create_table('reports',
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('target_title', sa.String(length=200), nullable=False),
    sa.Column('reporter_id', sa.Uuid(), nullable=True),
    sa.Column('reporter_name', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_status_id', 'reports', ['status', 'id'], unique=False)
    op.create_index('ix_reports_target', 'reports', ['type', 'target_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_name', sa.String(length=40), nullable=False),
    sa.Column('permission', sa.String(length=80), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name', 'permission')
    )
    op.create_table('starhope_ai_agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('service', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('top_p', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_starhope_ai_agents_user_id'), 'starhope_ai_agents', ['user_id'], unique=False)
    op.create_table('starhope_folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_starhope_folders_user_id'), 'starhope_folders', ['user_id'], unique=False)
    op.create_table('starhope_practice_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('question_ids', sa.Text(), nullable=False),
    sa.Column('answers', sa.Text(), nullable=False),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.Column('passing_grade', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_starhope_practice_sessions_user_id'), 'starhope_practice_sessions', ['user_id'], unique=False)
    op.create_table('starhope_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('folder_id', sa.String(length=36), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_starhope_questions_user_id'), 'starhope_questions', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task_definitions',
    sa.Column('key', sa.String(length=10), nullable=False),
    sa.Column('title_key', sa.String(length=120), nullable=False),
    sa.Column('desc_key', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('requirement_count', sa.Integer(), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('upload_sessions',
    sa.Column('upload_id', sa.String(length=64), nullable=False),
    sa.Column('uploader_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('upload_id')
    )
    op.create_index('ix_upload_sessions_created', 'upload_sessions', ['created_at'], unique=False)
    op.create_table('user_balances',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_behavior_stats',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('last_checkin_date', sa.String(length=10), nullable=True),
    sa.Column('checkin_streak', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_dim',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('account_level', sa.String(length=10), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_follows',
    sa.Column('follower_id', sa.Uuid(), nullable=False),
    sa.Column('following_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_user_follows_pair')
    )
    op.create_index('ix_user_follows_follower_created', 'user_follows', ['follower_id', 'created_at'], unique=False)
    op.create_index('ix_user_follows_following_created', 'user_follows', ['following_id', 'created_at'], unique=False)
    op.create_table('articles',
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('published', sa.DateTime(timezone=True), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('bookmarks', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['article_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_articles_category_published', 'articles', ['category_id', 'published'], unique=False)
    op.create_index('ix_articles_published', 'articles', ['published'], unique=False)
    op.create_table('blog_comments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['blog_comments.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['blog_series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_comments_parent_id'), 'blog_comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_blog_comments_series_id'), 'blog_comments', ['series_id'], unique=False)
    op.create_table('blog_content',
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sha3', sa.String(length=128), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['blog_series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'path', name='uq_blog_content_series_path')
    )
    op.create_index(op.f('ix_blog_content_series_id'), 'blog_content', ['series_id'], unique=False)
    op.create_table('blog_stars',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['blog_series.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'series_id')
    )
    op.create_index(op.f('ix_blog_stars_series_id'), 'blog_stars', ['series_id'], unique=False)
    op.create_table('board_bans',
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_board_bans_board_user', 'board_bans', ['board_id', 'user_id'], unique=False)
    op.create_table('board_follows',
    sa.Column('follower_id', sa.Uuid(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'board_id', name='uq_board_follows_pair')
    )
    op.create_index('ix_board_follows_board', 'board_follows', ['board_id'], unique=False)
    op.create_table('columns',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('author_name', sa.String(length=80), nullable=True),
    sa.Column('author_title', sa.String(length=80), nullable=True),
    sa.Column('author_bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('subscribe_count', sa.Integer(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('badges', sa.Text(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['column_applications.id'], ),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('exam_attempts',
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('answers', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent_s', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_attempts_exam_id'), 'exam_attempts', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_attempts_user_id'), 'exam_attempts', ['user_id'], unique=False)
    op.create_table('exam_certificates',
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('cert_no', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cert_no')
    )
    op.create_index(op.f('ix_exam_certificates_exam_id'), 'exam_certificates', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_certificates_user_id'), 'exam_certificates', ['user_id'], unique=False)
    op.create_table('exam_questions',
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('answer', sa.String(length=200), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_questions_exam_id'), 'exam_questions', ['exam_id'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role_in_project', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qa_question_images',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['qa_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qa_question_image_question', 'qa_question_images', ['question_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('achievement_id', sa.Uuid(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('unlocked', sa.Boolean(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    op.create_table('user_task_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('period_date', sa.String(length=10), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('rewarded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'task_id', 'period_date', name='uq_user_task_period')
    )
    op.create_table('article_comments',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['article_comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_comments_article_id'), 'article_comments', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_comments_user_id'), 'article_comments', ['user_id'], unique=False)
    op.create_table('article_likes',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'user_id')
    )
    op.create_table('article_tag',
    sa.Column('article_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    op.create_index(op.f('ix_article_tag_tag_id'), 'article_tag', ['tag_id'], unique=False)
    op.create_table('column_posts',
    sa.Column('column_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cover_image', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['column_id'], ['columns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_items',
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('column_id', sa.Uuid(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('qa_question_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('cover', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=True),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', coalesce(title,'') || ' ' || coalesce(excerpt,'') || ' ' || coalesce(content,'') || ' ' || coalesce(summary,'') || ' ' || coalesce(keywords,'') || ' ' || coalesce(tags,''))", persisted=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('bookmark_count', sa.Integer(), nullable=False),
    sa.Column('forward_count', sa.Integer(), nullable=False),
    sa.Column('counts_reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['column_id'], ['columns.id'], ),
    sa.ForeignKeyConstraint(['qa_question_id'], ['qa_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_content_board_pinned', 'content_items', ['board_id', 'is_pinned', 'id'], unique=False)
    op.create_index('ix_content_board_type_status', 'content_items', ['board_id', 'content_type', 'status', 'id'], unique=False)
    op.create_index('ix_content_content_trgm', 'content_items', ['content'], unique=False, postgresql_using='gin', postgresql_ops={'content': 'public.gin_trgm_ops'})
    op.create_index(op.f('ix_content_items_author_id'), 'content_items', ['author_id'], unique=False)
    op.create_index(op.f('ix_content_items_column_id'), 'content_items', ['column_id'], unique=False)
    op.create_index(op.f('ix_content_items_qa_question_id'), 'content_items', ['qa_question_id'], unique=False)
    op.create_index('ix_content_published', 'content_items', ['published_at'], unique=False)
    op.create_index('ix_content_search_vector', 'content_items', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_content_slug', 'content_items', ['slug'], unique=True)
    op.create_index('ix_content_status_pinned', 'content_items', ['status', 'is_pinned', 'id'], unique=False)
    op.create_index('ix_content_title_trgm', 'content_items', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'public.gin_trgm_ops'})
    op.create_index('ix_content_type_status_created', 'content_items', ['content_type', 'status', 'created_at', 'id'], unique=False)
    op.create_table('content_comments',
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['content_comments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_content_comments_item_floor', 'content_comments', ['content_id', 'floor_number'], unique=False)
    op.create_index(op.f('ix_content_comments_user_id'), 'content_comments', ['user_id'], unique=False)
    op.create_table('content_likes',
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('content_id', 'user_id')
    )
    op.create_table('interaction_favorites',
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'user_id')
    )
    op.create_index('ix_interaction_fav_user_created', 'interaction_favorites', ['user_id', 'created_at'], unique=False)
    op.create_table('interaction_view_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('public.uuid_generate_v7()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_id', name='uq_interaction_view_user_content')
    )
    op.create_index('ix_interaction_view_user_viewed', 'interaction_view_logs', ['user_id', 'viewed_at'], unique=False)
    op.create_index('ix_interaction_view_viewed', 'interaction_view_logs', ['viewed_at'], unique=False)
    op.create_index('ix_interaction_view_content', 'interaction_view_logs', ['content_id'], unique=False)
    # Treehole tables were introduced after the original baseline.
    _create_treehole_tables()
    # ### end Alembic commands ###
    # 全部表建完后置：TimescaleDB 装配（hypertable 要求表已存在；失败仅告警不中断）
    op.execute(TIMESCALE_DDL)


def downgrade() -> None:
    """Downgrade schema."""
    _drop_treehole_tables()
    # continuous aggregate `points_daily` 由应用启动时装配（core/db/init_db.py），不在本迁移内建，
    # 但它依赖 points_ledger 这个 hypertable——不先拆视图，DROP TABLE 会被 PG 以「被依赖」拒绝。
    # 幂等（IF EXISTS）：无 timescaledb 的环境下是空操作。
    op.execute("DROP MATERIALIZED VIEW IF EXISTS points_daily")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interaction_view_viewed', table_name='interaction_view_logs')
    op.drop_index('ix_interaction_view_content', table_name='interaction_view_logs')
    op.drop_index('ix_interaction_view_user_viewed', table_name='interaction_view_logs')
    op.drop_table('interaction_view_logs')
    op.drop_index('ix_interaction_fav_user_created', table_name='interaction_favorites')
    op.drop_table('interaction_favorites')
    op.drop_table('content_likes')
    op.drop_index(op.f('ix_content_comments_user_id'), table_name='content_comments')
    op.drop_index('ix_content_comments_item_floor', table_name='content_comments')
    op.drop_table('content_comments')
    op.drop_index('ix_content_type_status_created', table_name='content_items')
    op.drop_index('ix_content_title_trgm', table_name='content_items', postgresql_using='gin', postgresql_ops={'title': 'public.gin_trgm_ops'})
    op.drop_index('ix_content_status_pinned', table_name='content_items')
    op.drop_index('ix_content_slug', table_name='content_items')
    op.drop_index('ix_content_search_vector', table_name='content_items', postgresql_using='gin')
    op.drop_index('ix_content_published', table_name='content_items')
    op.drop_index(op.f('ix_content_items_qa_question_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_column_id'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_author_id'), table_name='content_items')
    op.drop_index('ix_content_content_trgm', table_name='content_items', postgresql_using='gin', postgresql_ops={'content': 'public.gin_trgm_ops'})
    op.drop_index('ix_content_board_type_status', table_name='content_items')
    op.drop_index('ix_content_board_pinned', table_name='content_items')
    op.drop_table('content_items')
    op.drop_table('column_posts')
    op.drop_index(op.f('ix_article_tag_tag_id'), table_name='article_tag')
    op.drop_table('article_tag')
    op.drop_table('article_likes')
    op.drop_index(op.f('ix_article_comments_user_id'), table_name='article_comments')
    op.drop_index(op.f('ix_article_comments_article_id'), table_name='article_comments')
    op.drop_table('article_comments')
    op.drop_table('user_task_progress')
    op.drop_table('user_achievements')
    op.drop_index('ix_qa_question_image_question', table_name='qa_question_images')
    op.drop_table('qa_question_images')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_exam_questions_exam_id'), table_name='exam_questions')
    op.drop_table('exam_questions')
    op.drop_index(op.f('ix_exam_certificates_user_id'), table_name='exam_certificates')
    op.drop_index(op.f('ix_exam_certificates_exam_id'), table_name='exam_certificates')
    op.drop_table('exam_certificates')
    op.drop_index(op.f('ix_exam_attempts_user_id'), table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_exam_id'), table_name='exam_attempts')
    op.drop_table('exam_attempts')
    op.drop_table('columns')
    op.drop_index('ix_board_follows_board', table_name='board_follows')
    op.drop_table('board_follows')
    op.drop_index('ix_board_bans_board_user', table_name='board_bans')
    op.drop_table('board_bans')
    op.drop_index(op.f('ix_blog_stars_series_id'), table_name='blog_stars')
    op.drop_table('blog_stars')
    op.drop_index(op.f('ix_blog_content_series_id'), table_name='blog_content')
    op.drop_table('blog_content')
    op.drop_index(op.f('ix_blog_comments_parent_id'), table_name='blog_comments')
    op.drop_index(op.f('ix_blog_comments_series_id'), table_name='blog_comments')
    op.drop_table('blog_comments')
    op.drop_index('ix_articles_published', table_name='articles')
    op.drop_index('ix_articles_category_published', table_name='articles')
    op.drop_table('articles')
    op.drop_index('ix_user_follows_following_created', table_name='user_follows')
    op.drop_index('ix_user_follows_follower_created', table_name='user_follows')
    op.drop_table('user_follows')
    op.drop_table('user_dim')
    op.drop_table('user_behavior_stats')
    op.drop_table('user_balances')
    op.drop_index('ix_upload_sessions_created', table_name='upload_sessions')
    op.drop_table('upload_sessions')
    op.drop_table('task_definitions')
    op.drop_table('tags')
    op.drop_index(op.f('ix_starhope_questions_user_id'), table_name='starhope_questions')
    op.drop_table('starhope_questions')
    op.drop_index(op.f('ix_starhope_practice_sessions_user_id'), table_name='starhope_practice_sessions')
    op.drop_table('starhope_practice_sessions')
    op.drop_index(op.f('ix_starhope_folders_user_id'), table_name='starhope_folders')
    op.drop_table('starhope_folders')
    op.drop_index(op.f('ix_starhope_ai_agents_user_id'), table_name='starhope_ai_agents')
    op.drop_table('starhope_ai_agents')
    op.drop_table('role_permissions')
    op.drop_index('ix_reports_target', table_name='reports')
    op.drop_index('ix_reports_status_id', table_name='reports')
    op.drop_table('reports')
    op.drop_constraint('fk_qa_answers_question_id', 'qa_answers', type_='foreignkey')
    op.drop_index('ix_qa_question_status_id', table_name='qa_questions')
    op.drop_index('ix_qa_questions_due', table_name='qa_questions')
    op.drop_index('ix_qa_questions_bounty_sort', table_name='qa_questions')
    op.drop_index('ix_qa_question_category_id', table_name='qa_questions')
    op.drop_table('qa_questions')
    op.drop_index('ix_qa_answer_question_accepted', table_name='qa_answers')
    op.drop_index('ix_qa_answer_question', table_name='qa_answers')
    op.drop_table('qa_answers')
    op.drop_constraint('fk_library_files_project', 'library_files', type_='foreignkey')
    op.drop_table('projects')
    op.drop_index('uq_project_applications_pending', table_name='project_applications', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('project_applications')
    op.drop_index('ix_ledger_created_delta', table_name='points_ledger')
    op.drop_table('points_ledger')
    op.drop_index('ix_outbox_scan', table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index('ix_outbox_archived_published_at', table_name='outbox_archived')
    op.drop_index(op.f('ix_outbox_archived_event_id'), table_name='outbox_archived')
    op.drop_table('outbox_archived')
    op.drop_table('outbox_event_keys')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_aggregate', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_tokens')
    op.drop_table('notification_preferences')
    op.drop_table('moderation_rules')
    op.drop_table('library_files')
    op.drop_index('ix_feed_items_user_cursor', table_name='feed_items')
    op.drop_index('ix_feed_items_source', table_name='feed_items')
    op.drop_table('feed_items')
    op.drop_table('feed_fanout_state')
    op.drop_table('exchange_items')
    op.drop_table('exams')
    op.drop_table('event_processed')
    op.drop_index(op.f('ix_event_failures_event_id'), table_name='event_failures')
    op.drop_table('event_failures')
    op.drop_index('uq_dlq_source_message_id', table_name='dlq_messages')
    op.drop_index(op.f('ix_dlq_messages_status'), table_name='dlq_messages')
    op.drop_index(op.f('ix_dlq_messages_routing_key'), table_name='dlq_messages')
    op.drop_table('dlq_messages')
    op.drop_table('column_applications')
    op.drop_index(op.f('ix_boards_parent_id'), table_name='boards')
    op.drop_table('boards')
    op.drop_table('board_applications')
    op.drop_table('blog_series')
    op.drop_table('blog_repo_quarantine')
    op.drop_table('article_categories')
    op.drop_table('achievements')
    # ### end Alembic commands ###


def _create_treehole_tables() -> None:
    op.create_table(
        "treehole_letters",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("owner_id", sa.String(64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("category", sa.String(32), nullable=False),
        sa.Column("privacy", sa.String(16), nullable=False),
        sa.Column("codename", sa.String(80), nullable=False),
        sa.Column("moods", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("sticker", sa.Text(), nullable=False),
        sa.Column("paper", sa.String(32), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True)),
        sa.Column("seal_until", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_treehole_letters_owner_id", "treehole_letters", ["owner_id"])
    op.create_index(
        "ix_treehole_letters_public", "treehole_letters", ["privacy", "created_at"]
    )

    op.create_table(
        "treehole_reactions",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("owner_id", sa.String(64), nullable=False),
        sa.Column(
            "letter_id",
            sa.String(36),
            sa.ForeignKey("treehole_letters.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("kind", sa.String(16), nullable=False),
        sa.UniqueConstraint("owner_id", "letter_id", "kind"),
    )
    op.create_index(
        "ix_treehole_reactions_owner_id", "treehole_reactions", ["owner_id"]
    )

    op.create_table(
        "treehole_conversations",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "letter_id",
            sa.String(36),
            sa.ForeignKey("treehole_letters.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("author_id", sa.String(64), nullable=False),
        sa.Column("replier_id", sa.String(64), nullable=False),
        sa.Column("replier_codename", sa.String(80), nullable=False),
        sa.Column("author_blocked", sa.Boolean(), nullable=False),
        sa.Column("replier_blocked", sa.Boolean(), nullable=False),
        sa.Column("author_hidden", sa.Boolean(), nullable=False),
        sa.Column("replier_hidden", sa.Boolean(), nullable=False),
        sa.Column("author_cleared_at", sa.DateTime(timezone=True)),
        sa.Column("replier_cleared_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("letter_id", "replier_id"),
    )
    op.create_index(
        "ix_treehole_conversations_author_id", "treehole_conversations", ["author_id"]
    )
    op.create_index(
        "ix_treehole_conversations_replier_id", "treehole_conversations", ["replier_id"]
    )
    op.create_table(
        "treehole_messages",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "conversation_id",
            sa.String(36),
            sa.ForeignKey("treehole_conversations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("sender_id", sa.String(64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("recalled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "treehole_bottles",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("owner_id", sa.String(64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("picked_by", sa.String(64)),
        sa.Column("reply", sa.Text()),
        sa.Column("replied_at", sa.DateTime(timezone=True)),
    )
    op.create_index("ix_treehole_bottles_owner_id", "treehole_bottles", ["owner_id"])
    op.create_table(
        "treehole_wishes",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("owner_id", sa.String(64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("lights", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_treehole_wishes_owner_id", "treehole_wishes", ["owner_id"])
    op.create_table(
        "treehole_wish_lights",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "wish_id",
            sa.String(36),
            sa.ForeignKey("treehole_wishes.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.String(64), nullable=False),
        sa.UniqueConstraint("wish_id", "owner_id"),
    )
    op.create_table(
        "treehole_reports",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("reporter_id", sa.String(64), nullable=False),
        sa.Column("target_type", sa.String(16), nullable=False),
        sa.Column("target_id", sa.String(36), nullable=False),
        sa.Column("reason", sa.String(80), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("reporter_id", "target_type", "target_id"),
    )


def _drop_treehole_tables() -> None:
    for table in (
        "treehole_reports",
        "treehole_wish_lights",
        "treehole_wishes",
        "treehole_bottles",
        "treehole_messages",
        "treehole_conversations",
        "treehole_reactions",
        "treehole_letters",
    ):
        op.drop_table(table)
